"""add user biodata fields

Revision ID: add61567ae5e
Revises: 
Create Date: 2025-05-31 16:57:37.872729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add61567ae5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('umur_satuan', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('hamil', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usia_kandungan', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('menyusui', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('umur_anak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'umur_anak')
    op.drop_column('users', 'menyusui')
    op.drop_column('users', 'usia_kandungan')
    op.drop_column('users', 'hamil')
    op.drop_column('users', 'umur_satuan')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
